//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTask.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFormat")]
    public interface IFormat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormat/FormatPrice", ReplyAction="http://tempuri.org/IFormat/FormatPriceResponse")]
        string FormatPrice(string price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormat/FormatPrice", ReplyAction="http://tempuri.org/IFormat/FormatPriceResponse")]
        System.Threading.Tasks.Task<string> FormatPriceAsync(string price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFormatChannel : InterviewTask.ServiceReference1.IFormat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormatClient : System.ServiceModel.ClientBase<InterviewTask.ServiceReference1.IFormat>, InterviewTask.ServiceReference1.IFormat {
        
        public FormatClient() {
        }
        
        public FormatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FormatPrice(string price) {
            return base.Channel.FormatPrice(price);
        }
        
        public System.Threading.Tasks.Task<string> FormatPriceAsync(string price) {
            return base.Channel.FormatPriceAsync(price);
        }
    }
}
